<a href="https://colab.research.google.com/github/nikhil7127/AIO/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

###BASICS

In [ ]:
nArray = np.array([1,2,3,4])

In [ ]:
mulDimArray = np.array([[1,2,3,4],[2,4,4,1]])

In [ ]:
print(mulDimArray.ndim) # dimension of the array
print(mulDimArray.size)
print(mulDimArray.shape)

2
8
(2, 4)


In [ ]:
mulDimArray.dtype

dtype('int64')

In [ ]:
dir(mulDimArray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

###CREATING NUMPY ARRAY

In [ ]:
np.zeros((4,4),dtype='int8')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [ ]:
np.ones((4,4),dtype='int8')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [ ]:
np.random.randint(1,10,(2,3))

array([[4, 6, 5],
       [8, 2, 7]])

In [ ]:
np.full((4,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [ ]:
np.empty((2,2),dtype='int8')

array([[-16,   7],
       [103,  51]], dtype=int8)

In [ ]:
np.identity(5,dtype="int8")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [ ]:
rand = [[1,2,3]]
np.repeat(rand,3,axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

### ACCESSING/ CHANGING VALUES IN ARRAY

In [ ]:
array = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
array[1,2] # similar to array[1][2]

8

In [ ]:
array[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [ ]:
array[:,-2:]

array([[ 4,  5],
       [ 9, 10]])

In [ ]:
array[::,::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

In [ ]:
array[1:] = [[9]]
array[:1] = [9,1,2,2,3]

In [ ]:
array = np.random.randint(0,100,(3,4,2))

In [ ]:
array[1,1,1] # or similary to array[1][1][1]

72

In [ ]:
array[1:,1:] = [[[10,20]],[[30,20]]]

In [ ]:
array

array([[[60, 54],
        [38, 93],
        [ 8, 38],
        [79, 92]],

       [[39, 78],
        [10, 20],
        [10, 20],
        [10, 20]],

       [[10, 56],
        [30, 20],
        [30, 20],
        [30, 20]]])

### MATHEMATICS USING NUMPY

In [ ]:
a = np.array([1,2,3,4])

In [ ]:
a += 2 # we can perform "-","+","\","*"

In [ ]:
c = np.array([[1,12,3],[4,5,6]])

In [ ]:
np.max(c,axis=1) # axis = 0 column and axis =1 is row

array([12,  6])

In [ ]:
one = np.array([1,2,3,4])
two = np.array([5,6,7,8])

In [ ]:
np.vstack((one,two,two,one))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [ ]:
np.hstack((one,two,two,one))

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8, 1, 2, 3, 4])

In [ ]:
stack = np.vstack((one,two,one,two))

In [ ]:
stack[stack > 2]

array([3, 4, 5, 6, 7, 8, 3, 4, 5, 6, 7, 8])

In [ ]:
stack[(stack >2) & (stack <10)]

array([3, 4, 5, 6, 7, 8, 3, 4, 5, 6, 7, 8])

In [ ]:
stack[[1,2,3],[2,1,1]] # stack[1][2] and stack[2][1] and stack[3][1]

array([7, 2, 6])